---
# This playbook will install a mail-server.
# Based on: https://workaround.org/ispmail/wheezy

- name: Install mail server
  hosts: all

  roles:
    - base
    - web
    - db
    - postfix
    - dovecot
#    - postgrey
    - roundcube
