---
# This role will setup the base installation

# Run the equivalent of "apt-get update" as a separate step
- apt: update_cache=yes

# Update all packages to the latest version
- apt: upgrade=dist

- name: Remove exim4
  apt: pkg=exim4 state=absent

- name: Install base packages
  action: apt pkg={{ item }} state=present
  with_items:
   - phpmyadmin

- name: Create soft link for phpMyAdmin
  command: ln -sf /usr/share/phpmyadmin /var/www/phpmyadmin
