---
# This playbook will install base software needed to do everything else

- name: Update and upgrade apt
  apt: update_cache=yes
-  apt: upgrade=dist

- name: Install base software
  action: apt pkg={{ item }} state=present
  with_items:
   - git

- name: Add github's SSH key
  command: mkdir -p /root/.ssh
- copy: src=known_hosts dest=/root/.ssh/known_hosts owner=root group=root mode=0600
