---
# This role will install and configure the Mail Admin Tool
# From: http://mat.ssdata.dk/

- name: Install Ruby dependency
  action: apt pkg={{ item }} state=present
  with_items:
   - ruby
   - ruby-rack
   - ruby-mysql
   - libmysql-ruby
   - libmysqlclient-dev
   - bundler
   - rake
   - libapache2-mod-passenger

- name: Download file
  get_url: url=http://mat.ssdata.dk/files/MATv1.2.1.tar.gz dest=/opt/
  
- name: Uncompress file
  command: tar xf /opt/MATv1.2.1.tar.gz -C /opt

- name: Fix configuration file
  lineinfile: dest=/opt/posty_webui/conf.js regexp="^.*serverUrl" line="var serverUrl = 'https://admin.tarek.org/posty_api';"
 
- name: Create mysql user for posty
  mysql_user: name=mailposty password=mailposty priv=mailserver.*:ALL host='localhost' state=present

- template: src=database.yml.j2 dest=/opt/posty_api/config/database.yml owner=root group=root mode=0644

- file: src=/opt/posty_webui dest=/home/web/admin/posty state=link

- command: a2enmod passenger