---
# This role will install and configure the Mail Admin Tool
# From: http://mat.ssdata.dk/

- name: Download file
  get_url: url=http://mat.ssdata.dk/files/MATv1.2.1.tar.gz dest=/opt/
  
- name: Uncompress file
  command: tar xf /opt/MATv1.2.1.tar.gz -C /opt

- name: Create Admin User for db with all privileges
  mysql_user: name={{ mailadmin_user }} password={{ mailadmin_pass }} priv={{ mailserver_db }}.*:ALL host='localhost' state=present

- name: Fix configuration file
  lineinfile: dest=/opt/MATv1.2.1/includes/config.php regexp="^.*DB_USER" line="        define('DB_USER', '{{ mailadmin_user }}'); //user for mysql must have SELECT, INSERT, UPDATE, DELETE rights to the mailserver database!"

- lineinfile: dest=/opt/MATv1.2.1/includes/config.php regexp="^.*DB_PASS" line="        define('DB_PASSWORD', '{{ mailadmin_pass }}'); //password for mysql"

- lineinfile: dest=/opt/MATv1.2.1/includes/config.php regexp="^.*username" line="        define('username', '{{ MAT_admin_user }}'); //username to access the site"

- lineinfile: dest=/opt/MATv1.2.1/includes/config.php regexp="^.*password" line="        define('password', '{{ MAT_admin_pass }}'); //password to access the site"