---
# This role will install and configure Roundcube

- name: Install Roundcube
  action: apt pkg={{ item }} state=present
  with_items:
   - roundcube
   - roundcube-plugins

- file: src=/usr/share/roundcube dest=/var/www/roundcube state=link

- name: Copy configuration files for plugins
  shell: cp /usr/share/roundcube/plugins/managesieve/config.inc.php.dist /etc/roundcube/plugins/managesieve/config.inc.php
- shell: cp /usr/share/roundcube/plugins/password/config.inc.php.dist /etc/roundcube/plugins/password/config.inc.php

- lineinfile: dest=/usr/share/roundcube/plugins/managesieve/config.inc.php regexp='^.*managesieve_port' line="$rcmail_config['managesieve_port'] = 4190;"

- lineinfile: dest=/etc/roundcube/main.inc.php regexp="^.*rcmail_config\[\'plugins\'\]" line="$rcmail_config['plugins'] = array('carddav', 'managesieve', 'password');"

- lineinfile: dest=/etc/roundcube/plugins/password/config.inc.php regexp="^.*rcmail_config\[\'password_query\'\]" line="$rcmail_config['password_query'] = 'UPDATE virtual_users SET `password` = MD5(%p) where `email` = %u';"

- lineinfile: dest=/etc/roundcube/plugins/password/config.inc.php regexp="^.*rcmail_config\[\'password_db_dsn\'\]" line="$rcmail_config['password_db_dsn'] = 'mysql://{{ mailpass_user }}:{{ mailpass_pass }}@{{ mailserver_host }}/{{ mailserver_db }}';"
