---
# This role will install and configure Roundcube

- name: Install Roundcube
  action: apt pkg={{ item }} state=present
  with_items:
   - roundcube
   - roundcube-plugins

- command: ln -sf /usr/share/roundcube /var/www/roundcube
