---
# This role will install and configure postfix

- name: Install Postfix
  action: apt pkg={{ item }} state=present
  with_items:
   - postfix
   - postfix-mysql
   - python-mysqldb

- name: Create Postfix Database
  mysql_db: name=mailserver state=present

- name: Create Postfix DB User with all privileges
  mysql_user: name={{ mailserver_user }} password={{ mailserver_password }} priv=mailserver.*:ALL host='localhost' state=present

- name: Upload and install SQL schema
  copy: src=setup.sql dest=/tmp/setup.sql

- shell: mysql -u {{ mailserver_user }} -p{{ mailserver_password }} mailserver < /tmp/setup.sql

- name: Return mailserver user privileges
  mysql_user: name={{ mailserver_user }} password={{ mailserver_password }} priv=mailserver.*:SELECT host='localhost' state=present

- name: Create mailpass user and set privileges
  mysql_user: name={{ mailpass_user }} password={{ mailpass_password }} priv=mailserver.*:SELECT,UPDATE host='localhost' state=present


- name: Upload configuration templates
  template: src=mysql-virtual-mailbox-domains.cf.j2 dest=/etc/postfix/mysql-virtual-mailbox-domains.cf owner=root group=root mode=0644
- template: src=mysql-virtual-mailbox-maps.cf.j2 dest=/etc/postfix/mysql-virtual-mailbox-maps.cf owner=root group=root mode=0644
- template: src=mysql-virtual-alias-maps.cf.j2 dest=/etc/postfix/mysql-virtual-alias-maps.cf owner=root group=root mode=0644

- name: Update configurations
  shell: postconf -e virtual_mailbox_domains=mysql:/etc/postfix/mysql-virtual-mailbox-domains.cf
- shell: postconf -e virtual_mailbox_maps=mysql:/etc/postfix/mysql-virtual-mailbox-maps.cf
- shell: postconf -e virtual_alias_maps=mysql:/etc/postfix/mysql-virtual-alias-maps.cf
- shell: postconf -e virtual_transport=dovecot
- shell: postconf -e dovecot_destination_recipient_limit=1
- shell: postconf -e smtpd_sasl_type=dovecot
- shell: postconf -e smtpd_sasl_path=private/auth
- shell: postconf -e smtpd_sasl_auth_enable=yes
- shell: postconf -e smtpd_tls_security_level=may
- shell: postconf -e smtpd_tls_auth_only=yes
- shell: postconf -e smtpd_tls_cert_file=/etc/ssl/certs/mailserver.pem
- shell: postconf -e smtpd_tls_key_file=/etc/ssl/private/mailserver.pem
- shell: postconf -e smtpd_recipient_restrictions="permit_mynetworks, permit_sasl_authenticated, reject_unauth_pipelining, reject_rbl_client bl.spamcop.net, reject_rbl_client zen.spamhaus.org, reject_unknown_client_hostname, reject_unknown_sender_domain, reject_unauth_destination"
- script: postfix-add-dovecot.sh

- service: name=postfix state=restarted
